/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsPaymentLinksRouteImport } from './routes/products.payment-links'
import { Route as ProductsPayOutRouteImport } from './routes/products.pay-out'
import { Route as ProductsPayInRouteImport } from './routes/products.pay-in'
import { Route as ProductsEcommerceRouteImport } from './routes/products.ecommerce'
import { Route as PaySlugRouteImport } from './routes/pay.$slug'
import { Route as LegalTermsRouteImport } from './routes/legal.terms'
import { Route as LegalPrivacyRouteImport } from './routes/legal.privacy'
import { Route as LegalAmlRouteImport } from './routes/legal.aml'
import { Route as DevelopersSdksRouteImport } from './routes/developers.sdks'
import { Route as DevelopersApiRouteImport } from './routes/developers.api'
import { Route as CompanyPricingRouteImport } from './routes/company.pricing'
import { Route as CompanyCoverageRouteImport } from './routes/company.coverage'
import { Route as CompanyContactRouteImport } from './routes/company.contact'
import { Route as CompanyAboutRouteImport } from './routes/company.about'
import { Route as AuthSignUpRouteImport } from './routes/auth.sign-up'
import { Route as AuthSignInRouteImport } from './routes/auth.sign-in'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedCompleteProfileRouteImport } from './routes/_authenticated/complete-profile'
import { Route as AuthenticatedDashboardRouteRouteImport } from './routes/_authenticated/dashboard/route'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard/index'
import { Route as AdminAdminIndexRouteImport } from './routes/_admin/admin/index'
import { Route as ApiV1PayoutsRouteImport } from './routes/api/v1/payouts'
import { Route as ApiV1ChargesRouteImport } from './routes/api/v1/charges'
import { Route as ApiPublicWithdrawRouteImport } from './routes/api/public/withdraw'
import { Route as ApiPublicTestNotifyRouteImport } from './routes/api/public/test-notify'
import { Route as ApiPublicTestEmailRouteImport } from './routes/api/public/test-email'
import { Route as ApiPublicSyncWalletRouteImport } from './routes/api/public/sync-wallet'
import { Route as ApiPublicSendNotificationRouteImport } from './routes/api/public/send-notification'
import { Route as ApiPublicPawapayWebhookRouteImport } from './routes/api/public/pawapay-webhook'
import { Route as ApiPublicLigdicashWebhookRouteImport } from './routes/api/public/ligdicash-webhook'
import { Route as AuthenticatedDashboardWalletRouteImport } from './routes/_authenticated/dashboard/wallet'
import { Route as AuthenticatedDashboardVerifyRouteImport } from './routes/_authenticated/dashboard/verify'
import { Route as AuthenticatedDashboardTransactionsRouteImport } from './routes/_authenticated/dashboard/transactions'
import { Route as AuthenticatedDashboardTeamRouteImport } from './routes/_authenticated/dashboard/team'
import { Route as AuthenticatedDashboardSettingsRouteImport } from './routes/_authenticated/dashboard/settings'
import { Route as AuthenticatedDashboardPayoutsRouteImport } from './routes/_authenticated/dashboard/payouts'
import { Route as AuthenticatedDashboardPaymentLinksRouteImport } from './routes/_authenticated/dashboard/payment-links'
import { Route as AuthenticatedDashboardApiKeysRouteImport } from './routes/_authenticated/dashboard/api-keys'
import { Route as AuthenticatedDashboardAdminRouteImport } from './routes/_authenticated/dashboard/admin'
import { Route as AdminAdminTeamRouteImport } from './routes/_admin/admin/team'
import { Route as AdminAdminKycRouteImport } from './routes/_admin/admin/kyc'
import { Route as ApiV1ChargesIdRouteImport } from './routes/api/v1/charges.$id'
import { Route as ApiPublicTxTimeoutIdRouteImport } from './routes/api/public/tx-timeout.$id'
import { Route as ApiPublicTxStatusIdRouteImport } from './routes/api/public/tx-status.$id'
import { Route as ApiPublicPaySlugRouteImport } from './routes/api/public/pay.$slug'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsPaymentLinksRoute = ProductsPaymentLinksRouteImport.update({
  id: '/products/payment-links',
  path: '/products/payment-links',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsPayOutRoute = ProductsPayOutRouteImport.update({
  id: '/products/pay-out',
  path: '/products/pay-out',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsPayInRoute = ProductsPayInRouteImport.update({
  id: '/products/pay-in',
  path: '/products/pay-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsEcommerceRoute = ProductsEcommerceRouteImport.update({
  id: '/products/ecommerce',
  path: '/products/ecommerce',
  getParentRoute: () => rootRouteImport,
} as any)
const PaySlugRoute = PaySlugRouteImport.update({
  id: '/pay/$slug',
  path: '/pay/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalAmlRoute = LegalAmlRouteImport.update({
  id: '/legal/aml',
  path: '/legal/aml',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopersSdksRoute = DevelopersSdksRouteImport.update({
  id: '/developers/sdks',
  path: '/developers/sdks',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopersApiRoute = DevelopersApiRouteImport.update({
  id: '/developers/api',
  path: '/developers/api',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyPricingRoute = CompanyPricingRouteImport.update({
  id: '/company/pricing',
  path: '/company/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyCoverageRoute = CompanyCoverageRouteImport.update({
  id: '/company/coverage',
  path: '/company/coverage',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyContactRoute = CompanyContactRouteImport.update({
  id: '/company/contact',
  path: '/company/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyAboutRoute = CompanyAboutRouteImport.update({
  id: '/company/about',
  path: '/company/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/auth/sign-up',
  path: '/auth/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCompleteProfileRoute =
  AuthenticatedCompleteProfileRouteImport.update({
    id: '/complete-profile',
    path: '/complete-profile',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRouteRoute =
  AuthenticatedDashboardRouteRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AdminAdminIndexRoute = AdminAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AdminRoute,
} as any)
const ApiV1PayoutsRoute = ApiV1PayoutsRouteImport.update({
  id: '/api/v1/payouts',
  path: '/api/v1/payouts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ChargesRoute = ApiV1ChargesRouteImport.update({
  id: '/api/v1/charges',
  path: '/api/v1/charges',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWithdrawRoute = ApiPublicWithdrawRouteImport.update({
  id: '/api/public/withdraw',
  path: '/api/public/withdraw',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTestNotifyRoute = ApiPublicTestNotifyRouteImport.update({
  id: '/api/public/test-notify',
  path: '/api/public/test-notify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTestEmailRoute = ApiPublicTestEmailRouteImport.update({
  id: '/api/public/test-email',
  path: '/api/public/test-email',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSyncWalletRoute = ApiPublicSyncWalletRouteImport.update({
  id: '/api/public/sync-wallet',
  path: '/api/public/sync-wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSendNotificationRoute =
  ApiPublicSendNotificationRouteImport.update({
    id: '/api/public/send-notification',
    path: '/api/public/send-notification',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPawapayWebhookRoute = ApiPublicPawapayWebhookRouteImport.update({
  id: '/api/public/pawapay-webhook',
  path: '/api/public/pawapay-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLigdicashWebhookRoute =
  ApiPublicLigdicashWebhookRouteImport.update({
    id: '/api/public/ligdicash-webhook',
    path: '/api/public/ligdicash-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedDashboardWalletRoute =
  AuthenticatedDashboardWalletRouteImport.update({
    id: '/wallet',
    path: '/wallet',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedDashboardVerifyRoute =
  AuthenticatedDashboardVerifyRouteImport.update({
    id: '/verify',
    path: '/verify',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedDashboardTransactionsRoute =
  AuthenticatedDashboardTransactionsRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedDashboardTeamRoute =
  AuthenticatedDashboardTeamRouteImport.update({
    id: '/team',
    path: '/team',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedDashboardSettingsRoute =
  AuthenticatedDashboardSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedDashboardPayoutsRoute =
  AuthenticatedDashboardPayoutsRouteImport.update({
    id: '/payouts',
    path: '/payouts',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedDashboardPaymentLinksRoute =
  AuthenticatedDashboardPaymentLinksRouteImport.update({
    id: '/payment-links',
    path: '/payment-links',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedDashboardApiKeysRoute =
  AuthenticatedDashboardApiKeysRouteImport.update({
    id: '/api-keys',
    path: '/api-keys',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedDashboardAdminRoute =
  AuthenticatedDashboardAdminRouteImport.update({
    id: '/admin',
    path: '/admin',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AdminAdminTeamRoute = AdminAdminTeamRouteImport.update({
  id: '/admin/team',
  path: '/admin/team',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminKycRoute = AdminAdminKycRouteImport.update({
  id: '/admin/kyc',
  path: '/admin/kyc',
  getParentRoute: () => AdminRoute,
} as any)
const ApiV1ChargesIdRoute = ApiV1ChargesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiV1ChargesRoute,
} as any)
const ApiPublicTxTimeoutIdRoute = ApiPublicTxTimeoutIdRouteImport.update({
  id: '/api/public/tx-timeout/$id',
  path: '/api/public/tx-timeout/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTxStatusIdRoute = ApiPublicTxStatusIdRouteImport.update({
  id: '/api/public/tx-status/$id',
  path: '/api/public/tx-status/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaySlugRoute = ApiPublicPaySlugRouteImport.update({
  id: '/api/public/pay/$slug',
  path: '/api/public/pay/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/dashboard': typeof AuthenticatedDashboardRouteRouteWithChildren
  '/complete-profile': typeof AuthenticatedCompleteProfileRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/company/about': typeof CompanyAboutRoute
  '/company/contact': typeof CompanyContactRoute
  '/company/coverage': typeof CompanyCoverageRoute
  '/company/pricing': typeof CompanyPricingRoute
  '/developers/api': typeof DevelopersApiRoute
  '/developers/sdks': typeof DevelopersSdksRoute
  '/legal/aml': typeof LegalAmlRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/pay/$slug': typeof PaySlugRoute
  '/products/ecommerce': typeof ProductsEcommerceRoute
  '/products/pay-in': typeof ProductsPayInRoute
  '/products/pay-out': typeof ProductsPayOutRoute
  '/products/payment-links': typeof ProductsPaymentLinksRoute
  '/admin/kyc': typeof AdminAdminKycRoute
  '/admin/team': typeof AdminAdminTeamRoute
  '/dashboard/admin': typeof AuthenticatedDashboardAdminRoute
  '/dashboard/api-keys': typeof AuthenticatedDashboardApiKeysRoute
  '/dashboard/payment-links': typeof AuthenticatedDashboardPaymentLinksRoute
  '/dashboard/payouts': typeof AuthenticatedDashboardPayoutsRoute
  '/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/dashboard/team': typeof AuthenticatedDashboardTeamRoute
  '/dashboard/transactions': typeof AuthenticatedDashboardTransactionsRoute
  '/dashboard/verify': typeof AuthenticatedDashboardVerifyRoute
  '/dashboard/wallet': typeof AuthenticatedDashboardWalletRoute
  '/api/public/ligdicash-webhook': typeof ApiPublicLigdicashWebhookRoute
  '/api/public/pawapay-webhook': typeof ApiPublicPawapayWebhookRoute
  '/api/public/send-notification': typeof ApiPublicSendNotificationRoute
  '/api/public/sync-wallet': typeof ApiPublicSyncWalletRoute
  '/api/public/test-email': typeof ApiPublicTestEmailRoute
  '/api/public/test-notify': typeof ApiPublicTestNotifyRoute
  '/api/public/withdraw': typeof ApiPublicWithdrawRoute
  '/api/v1/charges': typeof ApiV1ChargesRouteWithChildren
  '/api/v1/payouts': typeof ApiV1PayoutsRoute
  '/admin/': typeof AdminAdminIndexRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/api/public/pay/$slug': typeof ApiPublicPaySlugRoute
  '/api/public/tx-status/$id': typeof ApiPublicTxStatusIdRoute
  '/api/public/tx-timeout/$id': typeof ApiPublicTxTimeoutIdRoute
  '/api/v1/charges/$id': typeof ApiV1ChargesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/complete-profile': typeof AuthenticatedCompleteProfileRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/company/about': typeof CompanyAboutRoute
  '/company/contact': typeof CompanyContactRoute
  '/company/coverage': typeof CompanyCoverageRoute
  '/company/pricing': typeof CompanyPricingRoute
  '/developers/api': typeof DevelopersApiRoute
  '/developers/sdks': typeof DevelopersSdksRoute
  '/legal/aml': typeof LegalAmlRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/pay/$slug': typeof PaySlugRoute
  '/products/ecommerce': typeof ProductsEcommerceRoute
  '/products/pay-in': typeof ProductsPayInRoute
  '/products/pay-out': typeof ProductsPayOutRoute
  '/products/payment-links': typeof ProductsPaymentLinksRoute
  '/admin/kyc': typeof AdminAdminKycRoute
  '/admin/team': typeof AdminAdminTeamRoute
  '/dashboard/admin': typeof AuthenticatedDashboardAdminRoute
  '/dashboard/api-keys': typeof AuthenticatedDashboardApiKeysRoute
  '/dashboard/payment-links': typeof AuthenticatedDashboardPaymentLinksRoute
  '/dashboard/payouts': typeof AuthenticatedDashboardPayoutsRoute
  '/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/dashboard/team': typeof AuthenticatedDashboardTeamRoute
  '/dashboard/transactions': typeof AuthenticatedDashboardTransactionsRoute
  '/dashboard/verify': typeof AuthenticatedDashboardVerifyRoute
  '/dashboard/wallet': typeof AuthenticatedDashboardWalletRoute
  '/api/public/ligdicash-webhook': typeof ApiPublicLigdicashWebhookRoute
  '/api/public/pawapay-webhook': typeof ApiPublicPawapayWebhookRoute
  '/api/public/send-notification': typeof ApiPublicSendNotificationRoute
  '/api/public/sync-wallet': typeof ApiPublicSyncWalletRoute
  '/api/public/test-email': typeof ApiPublicTestEmailRoute
  '/api/public/test-notify': typeof ApiPublicTestNotifyRoute
  '/api/public/withdraw': typeof ApiPublicWithdrawRoute
  '/api/v1/charges': typeof ApiV1ChargesRouteWithChildren
  '/api/v1/payouts': typeof ApiV1PayoutsRoute
  '/admin': typeof AdminAdminIndexRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/api/public/pay/$slug': typeof ApiPublicPaySlugRoute
  '/api/public/tx-status/$id': typeof ApiPublicTxStatusIdRoute
  '/api/public/tx-timeout/$id': typeof ApiPublicTxTimeoutIdRoute
  '/api/v1/charges/$id': typeof ApiV1ChargesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_admin': typeof AdminRouteWithChildren
  '/settings': typeof SettingsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteRouteWithChildren
  '/_authenticated/complete-profile': typeof AuthenticatedCompleteProfileRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/company/about': typeof CompanyAboutRoute
  '/company/contact': typeof CompanyContactRoute
  '/company/coverage': typeof CompanyCoverageRoute
  '/company/pricing': typeof CompanyPricingRoute
  '/developers/api': typeof DevelopersApiRoute
  '/developers/sdks': typeof DevelopersSdksRoute
  '/legal/aml': typeof LegalAmlRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/pay/$slug': typeof PaySlugRoute
  '/products/ecommerce': typeof ProductsEcommerceRoute
  '/products/pay-in': typeof ProductsPayInRoute
  '/products/pay-out': typeof ProductsPayOutRoute
  '/products/payment-links': typeof ProductsPaymentLinksRoute
  '/_admin/admin/kyc': typeof AdminAdminKycRoute
  '/_admin/admin/team': typeof AdminAdminTeamRoute
  '/_authenticated/dashboard/admin': typeof AuthenticatedDashboardAdminRoute
  '/_authenticated/dashboard/api-keys': typeof AuthenticatedDashboardApiKeysRoute
  '/_authenticated/dashboard/payment-links': typeof AuthenticatedDashboardPaymentLinksRoute
  '/_authenticated/dashboard/payouts': typeof AuthenticatedDashboardPayoutsRoute
  '/_authenticated/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/_authenticated/dashboard/team': typeof AuthenticatedDashboardTeamRoute
  '/_authenticated/dashboard/transactions': typeof AuthenticatedDashboardTransactionsRoute
  '/_authenticated/dashboard/verify': typeof AuthenticatedDashboardVerifyRoute
  '/_authenticated/dashboard/wallet': typeof AuthenticatedDashboardWalletRoute
  '/api/public/ligdicash-webhook': typeof ApiPublicLigdicashWebhookRoute
  '/api/public/pawapay-webhook': typeof ApiPublicPawapayWebhookRoute
  '/api/public/send-notification': typeof ApiPublicSendNotificationRoute
  '/api/public/sync-wallet': typeof ApiPublicSyncWalletRoute
  '/api/public/test-email': typeof ApiPublicTestEmailRoute
  '/api/public/test-notify': typeof ApiPublicTestNotifyRoute
  '/api/public/withdraw': typeof ApiPublicWithdrawRoute
  '/api/v1/charges': typeof ApiV1ChargesRouteWithChildren
  '/api/v1/payouts': typeof ApiV1PayoutsRoute
  '/_admin/admin/': typeof AdminAdminIndexRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/api/public/pay/$slug': typeof ApiPublicPaySlugRoute
  '/api/public/tx-status/$id': typeof ApiPublicTxStatusIdRoute
  '/api/public/tx-timeout/$id': typeof ApiPublicTxTimeoutIdRoute
  '/api/v1/charges/$id': typeof ApiV1ChargesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/dashboard'
    | '/complete-profile'
    | '/onboarding'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/company/about'
    | '/company/contact'
    | '/company/coverage'
    | '/company/pricing'
    | '/developers/api'
    | '/developers/sdks'
    | '/legal/aml'
    | '/legal/privacy'
    | '/legal/terms'
    | '/pay/$slug'
    | '/products/ecommerce'
    | '/products/pay-in'
    | '/products/pay-out'
    | '/products/payment-links'
    | '/admin/kyc'
    | '/admin/team'
    | '/dashboard/admin'
    | '/dashboard/api-keys'
    | '/dashboard/payment-links'
    | '/dashboard/payouts'
    | '/dashboard/settings'
    | '/dashboard/team'
    | '/dashboard/transactions'
    | '/dashboard/verify'
    | '/dashboard/wallet'
    | '/api/public/ligdicash-webhook'
    | '/api/public/pawapay-webhook'
    | '/api/public/send-notification'
    | '/api/public/sync-wallet'
    | '/api/public/test-email'
    | '/api/public/test-notify'
    | '/api/public/withdraw'
    | '/api/v1/charges'
    | '/api/v1/payouts'
    | '/admin/'
    | '/dashboard/'
    | '/api/public/pay/$slug'
    | '/api/public/tx-status/$id'
    | '/api/public/tx-timeout/$id'
    | '/api/v1/charges/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/complete-profile'
    | '/onboarding'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/company/about'
    | '/company/contact'
    | '/company/coverage'
    | '/company/pricing'
    | '/developers/api'
    | '/developers/sdks'
    | '/legal/aml'
    | '/legal/privacy'
    | '/legal/terms'
    | '/pay/$slug'
    | '/products/ecommerce'
    | '/products/pay-in'
    | '/products/pay-out'
    | '/products/payment-links'
    | '/admin/kyc'
    | '/admin/team'
    | '/dashboard/admin'
    | '/dashboard/api-keys'
    | '/dashboard/payment-links'
    | '/dashboard/payouts'
    | '/dashboard/settings'
    | '/dashboard/team'
    | '/dashboard/transactions'
    | '/dashboard/verify'
    | '/dashboard/wallet'
    | '/api/public/ligdicash-webhook'
    | '/api/public/pawapay-webhook'
    | '/api/public/send-notification'
    | '/api/public/sync-wallet'
    | '/api/public/test-email'
    | '/api/public/test-notify'
    | '/api/public/withdraw'
    | '/api/v1/charges'
    | '/api/v1/payouts'
    | '/admin'
    | '/dashboard'
    | '/api/public/pay/$slug'
    | '/api/public/tx-status/$id'
    | '/api/public/tx-timeout/$id'
    | '/api/v1/charges/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_admin'
    | '/settings'
    | '/_authenticated/dashboard'
    | '/_authenticated/complete-profile'
    | '/_authenticated/onboarding'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/company/about'
    | '/company/contact'
    | '/company/coverage'
    | '/company/pricing'
    | '/developers/api'
    | '/developers/sdks'
    | '/legal/aml'
    | '/legal/privacy'
    | '/legal/terms'
    | '/pay/$slug'
    | '/products/ecommerce'
    | '/products/pay-in'
    | '/products/pay-out'
    | '/products/payment-links'
    | '/_admin/admin/kyc'
    | '/_admin/admin/team'
    | '/_authenticated/dashboard/admin'
    | '/_authenticated/dashboard/api-keys'
    | '/_authenticated/dashboard/payment-links'
    | '/_authenticated/dashboard/payouts'
    | '/_authenticated/dashboard/settings'
    | '/_authenticated/dashboard/team'
    | '/_authenticated/dashboard/transactions'
    | '/_authenticated/dashboard/verify'
    | '/_authenticated/dashboard/wallet'
    | '/api/public/ligdicash-webhook'
    | '/api/public/pawapay-webhook'
    | '/api/public/send-notification'
    | '/api/public/sync-wallet'
    | '/api/public/test-email'
    | '/api/public/test-notify'
    | '/api/public/withdraw'
    | '/api/v1/charges'
    | '/api/v1/payouts'
    | '/_admin/admin/'
    | '/_authenticated/dashboard/'
    | '/api/public/pay/$slug'
    | '/api/public/tx-status/$id'
    | '/api/public/tx-timeout/$id'
    | '/api/v1/charges/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  CompanyAboutRoute: typeof CompanyAboutRoute
  CompanyContactRoute: typeof CompanyContactRoute
  CompanyCoverageRoute: typeof CompanyCoverageRoute
  CompanyPricingRoute: typeof CompanyPricingRoute
  DevelopersApiRoute: typeof DevelopersApiRoute
  DevelopersSdksRoute: typeof DevelopersSdksRoute
  LegalAmlRoute: typeof LegalAmlRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalTermsRoute: typeof LegalTermsRoute
  PaySlugRoute: typeof PaySlugRoute
  ProductsEcommerceRoute: typeof ProductsEcommerceRoute
  ProductsPayInRoute: typeof ProductsPayInRoute
  ProductsPayOutRoute: typeof ProductsPayOutRoute
  ProductsPaymentLinksRoute: typeof ProductsPaymentLinksRoute
  ApiPublicLigdicashWebhookRoute: typeof ApiPublicLigdicashWebhookRoute
  ApiPublicPawapayWebhookRoute: typeof ApiPublicPawapayWebhookRoute
  ApiPublicSendNotificationRoute: typeof ApiPublicSendNotificationRoute
  ApiPublicSyncWalletRoute: typeof ApiPublicSyncWalletRoute
  ApiPublicTestEmailRoute: typeof ApiPublicTestEmailRoute
  ApiPublicTestNotifyRoute: typeof ApiPublicTestNotifyRoute
  ApiPublicWithdrawRoute: typeof ApiPublicWithdrawRoute
  ApiV1ChargesRoute: typeof ApiV1ChargesRouteWithChildren
  ApiV1PayoutsRoute: typeof ApiV1PayoutsRoute
  ApiPublicPaySlugRoute: typeof ApiPublicPaySlugRoute
  ApiPublicTxStatusIdRoute: typeof ApiPublicTxStatusIdRoute
  ApiPublicTxTimeoutIdRoute: typeof ApiPublicTxTimeoutIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/payment-links': {
      id: '/products/payment-links'
      path: '/products/payment-links'
      fullPath: '/products/payment-links'
      preLoaderRoute: typeof ProductsPaymentLinksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/pay-out': {
      id: '/products/pay-out'
      path: '/products/pay-out'
      fullPath: '/products/pay-out'
      preLoaderRoute: typeof ProductsPayOutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/pay-in': {
      id: '/products/pay-in'
      path: '/products/pay-in'
      fullPath: '/products/pay-in'
      preLoaderRoute: typeof ProductsPayInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/ecommerce': {
      id: '/products/ecommerce'
      path: '/products/ecommerce'
      fullPath: '/products/ecommerce'
      preLoaderRoute: typeof ProductsEcommerceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay/$slug': {
      id: '/pay/$slug'
      path: '/pay/$slug'
      fullPath: '/pay/$slug'
      preLoaderRoute: typeof PaySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/aml': {
      id: '/legal/aml'
      path: '/legal/aml'
      fullPath: '/legal/aml'
      preLoaderRoute: typeof LegalAmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developers/sdks': {
      id: '/developers/sdks'
      path: '/developers/sdks'
      fullPath: '/developers/sdks'
      preLoaderRoute: typeof DevelopersSdksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developers/api': {
      id: '/developers/api'
      path: '/developers/api'
      fullPath: '/developers/api'
      preLoaderRoute: typeof DevelopersApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/pricing': {
      id: '/company/pricing'
      path: '/company/pricing'
      fullPath: '/company/pricing'
      preLoaderRoute: typeof CompanyPricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/coverage': {
      id: '/company/coverage'
      path: '/company/coverage'
      fullPath: '/company/coverage'
      preLoaderRoute: typeof CompanyCoverageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/contact': {
      id: '/company/contact'
      path: '/company/contact'
      fullPath: '/company/contact'
      preLoaderRoute: typeof CompanyContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/about': {
      id: '/company/about'
      path: '/company/about'
      fullPath: '/company/about'
      preLoaderRoute: typeof CompanyAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/auth/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/complete-profile': {
      id: '/_authenticated/complete-profile'
      path: '/complete-profile'
      fullPath: '/complete-profile'
      preLoaderRoute: typeof AuthenticatedCompleteProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_admin/admin/': {
      id: '/_admin/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminAdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/v1/payouts': {
      id: '/api/v1/payouts'
      path: '/api/v1/payouts'
      fullPath: '/api/v1/payouts'
      preLoaderRoute: typeof ApiV1PayoutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/charges': {
      id: '/api/v1/charges'
      path: '/api/v1/charges'
      fullPath: '/api/v1/charges'
      preLoaderRoute: typeof ApiV1ChargesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/withdraw': {
      id: '/api/public/withdraw'
      path: '/api/public/withdraw'
      fullPath: '/api/public/withdraw'
      preLoaderRoute: typeof ApiPublicWithdrawRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/test-notify': {
      id: '/api/public/test-notify'
      path: '/api/public/test-notify'
      fullPath: '/api/public/test-notify'
      preLoaderRoute: typeof ApiPublicTestNotifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/test-email': {
      id: '/api/public/test-email'
      path: '/api/public/test-email'
      fullPath: '/api/public/test-email'
      preLoaderRoute: typeof ApiPublicTestEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sync-wallet': {
      id: '/api/public/sync-wallet'
      path: '/api/public/sync-wallet'
      fullPath: '/api/public/sync-wallet'
      preLoaderRoute: typeof ApiPublicSyncWalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/send-notification': {
      id: '/api/public/send-notification'
      path: '/api/public/send-notification'
      fullPath: '/api/public/send-notification'
      preLoaderRoute: typeof ApiPublicSendNotificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/pawapay-webhook': {
      id: '/api/public/pawapay-webhook'
      path: '/api/public/pawapay-webhook'
      fullPath: '/api/public/pawapay-webhook'
      preLoaderRoute: typeof ApiPublicPawapayWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ligdicash-webhook': {
      id: '/api/public/ligdicash-webhook'
      path: '/api/public/ligdicash-webhook'
      fullPath: '/api/public/ligdicash-webhook'
      preLoaderRoute: typeof ApiPublicLigdicashWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard/wallet': {
      id: '/_authenticated/dashboard/wallet'
      path: '/wallet'
      fullPath: '/dashboard/wallet'
      preLoaderRoute: typeof AuthenticatedDashboardWalletRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/verify': {
      id: '/_authenticated/dashboard/verify'
      path: '/verify'
      fullPath: '/dashboard/verify'
      preLoaderRoute: typeof AuthenticatedDashboardVerifyRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/transactions': {
      id: '/_authenticated/dashboard/transactions'
      path: '/transactions'
      fullPath: '/dashboard/transactions'
      preLoaderRoute: typeof AuthenticatedDashboardTransactionsRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/team': {
      id: '/_authenticated/dashboard/team'
      path: '/team'
      fullPath: '/dashboard/team'
      preLoaderRoute: typeof AuthenticatedDashboardTeamRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/settings': {
      id: '/_authenticated/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof AuthenticatedDashboardSettingsRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/payouts': {
      id: '/_authenticated/dashboard/payouts'
      path: '/payouts'
      fullPath: '/dashboard/payouts'
      preLoaderRoute: typeof AuthenticatedDashboardPayoutsRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/payment-links': {
      id: '/_authenticated/dashboard/payment-links'
      path: '/payment-links'
      fullPath: '/dashboard/payment-links'
      preLoaderRoute: typeof AuthenticatedDashboardPaymentLinksRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/api-keys': {
      id: '/_authenticated/dashboard/api-keys'
      path: '/api-keys'
      fullPath: '/dashboard/api-keys'
      preLoaderRoute: typeof AuthenticatedDashboardApiKeysRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/admin': {
      id: '/_authenticated/dashboard/admin'
      path: '/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof AuthenticatedDashboardAdminRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_admin/admin/team': {
      id: '/_admin/admin/team'
      path: '/admin/team'
      fullPath: '/admin/team'
      preLoaderRoute: typeof AdminAdminTeamRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/kyc': {
      id: '/_admin/admin/kyc'
      path: '/admin/kyc'
      fullPath: '/admin/kyc'
      preLoaderRoute: typeof AdminAdminKycRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/v1/charges/$id': {
      id: '/api/v1/charges/$id'
      path: '/$id'
      fullPath: '/api/v1/charges/$id'
      preLoaderRoute: typeof ApiV1ChargesIdRouteImport
      parentRoute: typeof ApiV1ChargesRoute
    }
    '/api/public/tx-timeout/$id': {
      id: '/api/public/tx-timeout/$id'
      path: '/api/public/tx-timeout/$id'
      fullPath: '/api/public/tx-timeout/$id'
      preLoaderRoute: typeof ApiPublicTxTimeoutIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/tx-status/$id': {
      id: '/api/public/tx-status/$id'
      path: '/api/public/tx-status/$id'
      fullPath: '/api/public/tx-status/$id'
      preLoaderRoute: typeof ApiPublicTxStatusIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/pay/$slug': {
      id: '/api/public/pay/$slug'
      path: '/api/public/pay/$slug'
      fullPath: '/api/public/pay/$slug'
      preLoaderRoute: typeof ApiPublicPaySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedDashboardRouteRouteChildren {
  AuthenticatedDashboardAdminRoute: typeof AuthenticatedDashboardAdminRoute
  AuthenticatedDashboardApiKeysRoute: typeof AuthenticatedDashboardApiKeysRoute
  AuthenticatedDashboardPaymentLinksRoute: typeof AuthenticatedDashboardPaymentLinksRoute
  AuthenticatedDashboardPayoutsRoute: typeof AuthenticatedDashboardPayoutsRoute
  AuthenticatedDashboardSettingsRoute: typeof AuthenticatedDashboardSettingsRoute
  AuthenticatedDashboardTeamRoute: typeof AuthenticatedDashboardTeamRoute
  AuthenticatedDashboardTransactionsRoute: typeof AuthenticatedDashboardTransactionsRoute
  AuthenticatedDashboardVerifyRoute: typeof AuthenticatedDashboardVerifyRoute
  AuthenticatedDashboardWalletRoute: typeof AuthenticatedDashboardWalletRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
}

const AuthenticatedDashboardRouteRouteChildren: AuthenticatedDashboardRouteRouteChildren =
  {
    AuthenticatedDashboardAdminRoute: AuthenticatedDashboardAdminRoute,
    AuthenticatedDashboardApiKeysRoute: AuthenticatedDashboardApiKeysRoute,
    AuthenticatedDashboardPaymentLinksRoute:
      AuthenticatedDashboardPaymentLinksRoute,
    AuthenticatedDashboardPayoutsRoute: AuthenticatedDashboardPayoutsRoute,
    AuthenticatedDashboardSettingsRoute: AuthenticatedDashboardSettingsRoute,
    AuthenticatedDashboardTeamRoute: AuthenticatedDashboardTeamRoute,
    AuthenticatedDashboardTransactionsRoute:
      AuthenticatedDashboardTransactionsRoute,
    AuthenticatedDashboardVerifyRoute: AuthenticatedDashboardVerifyRoute,
    AuthenticatedDashboardWalletRoute: AuthenticatedDashboardWalletRoute,
    AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  }

const AuthenticatedDashboardRouteRouteWithChildren =
  AuthenticatedDashboardRouteRoute._addFileChildren(
    AuthenticatedDashboardRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRouteRoute: typeof AuthenticatedDashboardRouteRouteWithChildren
  AuthenticatedCompleteProfileRoute: typeof AuthenticatedCompleteProfileRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRouteRoute:
    AuthenticatedDashboardRouteRouteWithChildren,
  AuthenticatedCompleteProfileRoute: AuthenticatedCompleteProfileRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AdminRouteChildren {
  AdminAdminKycRoute: typeof AdminAdminKycRoute
  AdminAdminTeamRoute: typeof AdminAdminTeamRoute
  AdminAdminIndexRoute: typeof AdminAdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminKycRoute: AdminAdminKycRoute,
  AdminAdminTeamRoute: AdminAdminTeamRoute,
  AdminAdminIndexRoute: AdminAdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ApiV1ChargesRouteChildren {
  ApiV1ChargesIdRoute: typeof ApiV1ChargesIdRoute
}

const ApiV1ChargesRouteChildren: ApiV1ChargesRouteChildren = {
  ApiV1ChargesIdRoute: ApiV1ChargesIdRoute,
}

const ApiV1ChargesRouteWithChildren = ApiV1ChargesRoute._addFileChildren(
  ApiV1ChargesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  SettingsRoute: SettingsRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  CompanyAboutRoute: CompanyAboutRoute,
  CompanyContactRoute: CompanyContactRoute,
  CompanyCoverageRoute: CompanyCoverageRoute,
  CompanyPricingRoute: CompanyPricingRoute,
  DevelopersApiRoute: DevelopersApiRoute,
  DevelopersSdksRoute: DevelopersSdksRoute,
  LegalAmlRoute: LegalAmlRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalTermsRoute: LegalTermsRoute,
  PaySlugRoute: PaySlugRoute,
  ProductsEcommerceRoute: ProductsEcommerceRoute,
  ProductsPayInRoute: ProductsPayInRoute,
  ProductsPayOutRoute: ProductsPayOutRoute,
  ProductsPaymentLinksRoute: ProductsPaymentLinksRoute,
  ApiPublicLigdicashWebhookRoute: ApiPublicLigdicashWebhookRoute,
  ApiPublicPawapayWebhookRoute: ApiPublicPawapayWebhookRoute,
  ApiPublicSendNotificationRoute: ApiPublicSendNotificationRoute,
  ApiPublicSyncWalletRoute: ApiPublicSyncWalletRoute,
  ApiPublicTestEmailRoute: ApiPublicTestEmailRoute,
  ApiPublicTestNotifyRoute: ApiPublicTestNotifyRoute,
  ApiPublicWithdrawRoute: ApiPublicWithdrawRoute,
  ApiV1ChargesRoute: ApiV1ChargesRouteWithChildren,
  ApiV1PayoutsRoute: ApiV1PayoutsRoute,
  ApiPublicPaySlugRoute: ApiPublicPaySlugRoute,
  ApiPublicTxStatusIdRoute: ApiPublicTxStatusIdRoute,
  ApiPublicTxTimeoutIdRoute: ApiPublicTxTimeoutIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
