/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsPaymentLinksRouteImport } from './routes/products.payment-links'
import { Route as ProductsPayOutRouteImport } from './routes/products.pay-out'
import { Route as ProductsPayInRouteImport } from './routes/products.pay-in'
import { Route as ProductsEcommerceRouteImport } from './routes/products.ecommerce'
import { Route as PaySlugRouteImport } from './routes/pay.$slug'
import { Route as LegalTermsRouteImport } from './routes/legal.terms'
import { Route as LegalPrivacyRouteImport } from './routes/legal.privacy'
import { Route as LegalAmlRouteImport } from './routes/legal.aml'
import { Route as DevelopersSdksRouteImport } from './routes/developers.sdks'
import { Route as DevelopersApiRouteImport } from './routes/developers.api'
import { Route as CompanyPricingRouteImport } from './routes/company.pricing'
import { Route as CompanyContactRouteImport } from './routes/company.contact'
import { Route as CompanyAboutRouteImport } from './routes/company.about'
import { Route as AuthSignUpRouteImport } from './routes/auth.sign-up'
import { Route as AuthSignInRouteImport } from './routes/auth.sign-in'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedCompleteProfileRouteImport } from './routes/_authenticated/complete-profile'
import { Route as AuthenticatedDashboardRouteRouteImport } from './routes/_authenticated/dashboard/route'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard/index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as ApiWebhooksDiditRouteImport } from './routes/api/webhooks/didit'
import { Route as ApiV1PayoutsRouteImport } from './routes/api/v1/payouts'
import { Route as ApiV1ChargesRouteImport } from './routes/api/v1/charges'
import { Route as ApiPublicWithdrawRouteImport } from './routes/api/public/withdraw'
import { Route as ApiPublicSyncWalletRouteImport } from './routes/api/public/sync-wallet'
import { Route as ApiPublicSendNotificationRouteImport } from './routes/api/public/send-notification'
import { Route as ApiPublicPawapayWebhookRouteImport } from './routes/api/public/pawapay-webhook'
import { Route as ApiPublicLigdicashWebhookRouteImport } from './routes/api/public/ligdicash-webhook'
import { Route as ApiPublicDiditWebhookRouteImport } from './routes/api/public/didit-webhook'
import { Route as AuthenticatedDashboardWalletRouteImport } from './routes/_authenticated/dashboard/wallet'
import { Route as AuthenticatedDashboardVerifyRouteImport } from './routes/_authenticated/dashboard/verify'
import { Route as AuthenticatedDashboardTransactionsRouteImport } from './routes/_authenticated/dashboard/transactions'
import { Route as AuthenticatedDashboardTeamRouteImport } from './routes/_authenticated/dashboard/team'
import { Route as AuthenticatedDashboardSettingsRouteImport } from './routes/_authenticated/dashboard/settings'
import { Route as AuthenticatedDashboardPayoutsRouteImport } from './routes/_authenticated/dashboard/payouts'
import { Route as AuthenticatedDashboardPaymentLinksRouteImport } from './routes/_authenticated/dashboard/payment-links'
import { Route as AuthenticatedDashboardApiKeysRouteImport } from './routes/_authenticated/dashboard/api-keys'
import { Route as AuthenticatedDashboardAdminRouteImport } from './routes/_authenticated/dashboard/admin'
import { Route as AuthenticatedAdminRiskRouteImport } from './routes/_authenticated/admin/risk'
import { Route as AuthenticatedAdminMerchantsRouteImport } from './routes/_authenticated/admin/merchants'
import { Route as AuthenticatedAdminLiveRouteImport } from './routes/_authenticated/admin/live'
import { Route as AuthenticatedAdminFinanceRouteImport } from './routes/_authenticated/admin/finance'
import { Route as AuthenticatedAdminComplianceRouteImport } from './routes/_authenticated/admin/compliance'
import { Route as AuthenticatedAdminAuditRouteImport } from './routes/_authenticated/admin/audit'
import { Route as ApiV1ChargesIdRouteImport } from './routes/api/v1/charges.$id'
import { Route as ApiPublicTxTimeoutIdRouteImport } from './routes/api/public/tx-timeout.$id'
import { Route as ApiPublicTxStatusIdRouteImport } from './routes/api/public/tx-status.$id'
import { Route as ApiPublicPaySlugRouteImport } from './routes/api/public/pay.$slug'
import { Route as AuthenticatedAdminMerchantsIdRouteImport } from './routes/_authenticated/admin/merchants.$id'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsPaymentLinksRoute = ProductsPaymentLinksRouteImport.update({
  id: '/products/payment-links',
  path: '/products/payment-links',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsPayOutRoute = ProductsPayOutRouteImport.update({
  id: '/products/pay-out',
  path: '/products/pay-out',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsPayInRoute = ProductsPayInRouteImport.update({
  id: '/products/pay-in',
  path: '/products/pay-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsEcommerceRoute = ProductsEcommerceRouteImport.update({
  id: '/products/ecommerce',
  path: '/products/ecommerce',
  getParentRoute: () => rootRouteImport,
} as any)
const PaySlugRoute = PaySlugRouteImport.update({
  id: '/pay/$slug',
  path: '/pay/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalAmlRoute = LegalAmlRouteImport.update({
  id: '/legal/aml',
  path: '/legal/aml',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopersSdksRoute = DevelopersSdksRouteImport.update({
  id: '/developers/sdks',
  path: '/developers/sdks',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopersApiRoute = DevelopersApiRouteImport.update({
  id: '/developers/api',
  path: '/developers/api',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyPricingRoute = CompanyPricingRouteImport.update({
  id: '/company/pricing',
  path: '/company/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyContactRoute = CompanyContactRouteImport.update({
  id: '/company/contact',
  path: '/company/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyAboutRoute = CompanyAboutRouteImport.update({
  id: '/company/about',
  path: '/company/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/auth/sign-up',
  path: '/auth/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCompleteProfileRoute =
  AuthenticatedCompleteProfileRouteImport.update({
    id: '/complete-profile',
    path: '/complete-profile',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRouteRoute =
  AuthenticatedDashboardRouteRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const ApiWebhooksDiditRoute = ApiWebhooksDiditRouteImport.update({
  id: '/api/webhooks/didit',
  path: '/api/webhooks/didit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1PayoutsRoute = ApiV1PayoutsRouteImport.update({
  id: '/api/v1/payouts',
  path: '/api/v1/payouts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ChargesRoute = ApiV1ChargesRouteImport.update({
  id: '/api/v1/charges',
  path: '/api/v1/charges',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWithdrawRoute = ApiPublicWithdrawRouteImport.update({
  id: '/api/public/withdraw',
  path: '/api/public/withdraw',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSyncWalletRoute = ApiPublicSyncWalletRouteImport.update({
  id: '/api/public/sync-wallet',
  path: '/api/public/sync-wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSendNotificationRoute =
  ApiPublicSendNotificationRouteImport.update({
    id: '/api/public/send-notification',
    path: '/api/public/send-notification',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPawapayWebhookRoute = ApiPublicPawapayWebhookRouteImport.update({
  id: '/api/public/pawapay-webhook',
  path: '/api/public/pawapay-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLigdicashWebhookRoute =
  ApiPublicLigdicashWebhookRouteImport.update({
    id: '/api/public/ligdicash-webhook',
    path: '/api/public/ligdicash-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicDiditWebhookRoute = ApiPublicDiditWebhookRouteImport.update({
  id: '/api/public/didit-webhook',
  path: '/api/public/didit-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardWalletRoute =
  AuthenticatedDashboardWalletRouteImport.update({
    id: '/wallet',
    path: '/wallet',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedDashboardVerifyRoute =
  AuthenticatedDashboardVerifyRouteImport.update({
    id: '/verify',
    path: '/verify',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedDashboardTransactionsRoute =
  AuthenticatedDashboardTransactionsRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedDashboardTeamRoute =
  AuthenticatedDashboardTeamRouteImport.update({
    id: '/team',
    path: '/team',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedDashboardSettingsRoute =
  AuthenticatedDashboardSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedDashboardPayoutsRoute =
  AuthenticatedDashboardPayoutsRouteImport.update({
    id: '/payouts',
    path: '/payouts',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedDashboardPaymentLinksRoute =
  AuthenticatedDashboardPaymentLinksRouteImport.update({
    id: '/payment-links',
    path: '/payment-links',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedDashboardApiKeysRoute =
  AuthenticatedDashboardApiKeysRouteImport.update({
    id: '/api-keys',
    path: '/api-keys',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedDashboardAdminRoute =
  AuthenticatedDashboardAdminRouteImport.update({
    id: '/admin',
    path: '/admin',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedAdminRiskRoute = AuthenticatedAdminRiskRouteImport.update({
  id: '/risk',
  path: '/risk',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminMerchantsRoute =
  AuthenticatedAdminMerchantsRouteImport.update({
    id: '/merchants',
    path: '/merchants',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminLiveRoute = AuthenticatedAdminLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminFinanceRoute =
  AuthenticatedAdminFinanceRouteImport.update({
    id: '/finance',
    path: '/finance',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminComplianceRoute =
  AuthenticatedAdminComplianceRouteImport.update({
    id: '/compliance',
    path: '/compliance',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAuditRoute = AuthenticatedAdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const ApiV1ChargesIdRoute = ApiV1ChargesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiV1ChargesRoute,
} as any)
const ApiPublicTxTimeoutIdRoute = ApiPublicTxTimeoutIdRouteImport.update({
  id: '/api/public/tx-timeout/$id',
  path: '/api/public/tx-timeout/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTxStatusIdRoute = ApiPublicTxStatusIdRouteImport.update({
  id: '/api/public/tx-status/$id',
  path: '/api/public/tx-status/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaySlugRoute = ApiPublicPaySlugRouteImport.update({
  id: '/api/public/pay/$slug',
  path: '/api/public/pay/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminMerchantsIdRoute =
  AuthenticatedAdminMerchantsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminMerchantsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRouteRouteWithChildren
  '/complete-profile': typeof AuthenticatedCompleteProfileRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/company/about': typeof CompanyAboutRoute
  '/company/contact': typeof CompanyContactRoute
  '/company/pricing': typeof CompanyPricingRoute
  '/developers/api': typeof DevelopersApiRoute
  '/developers/sdks': typeof DevelopersSdksRoute
  '/legal/aml': typeof LegalAmlRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/pay/$slug': typeof PaySlugRoute
  '/products/ecommerce': typeof ProductsEcommerceRoute
  '/products/pay-in': typeof ProductsPayInRoute
  '/products/pay-out': typeof ProductsPayOutRoute
  '/products/payment-links': typeof ProductsPaymentLinksRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/compliance': typeof AuthenticatedAdminComplianceRoute
  '/admin/finance': typeof AuthenticatedAdminFinanceRoute
  '/admin/live': typeof AuthenticatedAdminLiveRoute
  '/admin/merchants': typeof AuthenticatedAdminMerchantsRouteWithChildren
  '/admin/risk': typeof AuthenticatedAdminRiskRoute
  '/dashboard/admin': typeof AuthenticatedDashboardAdminRoute
  '/dashboard/api-keys': typeof AuthenticatedDashboardApiKeysRoute
  '/dashboard/payment-links': typeof AuthenticatedDashboardPaymentLinksRoute
  '/dashboard/payouts': typeof AuthenticatedDashboardPayoutsRoute
  '/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/dashboard/team': typeof AuthenticatedDashboardTeamRoute
  '/dashboard/transactions': typeof AuthenticatedDashboardTransactionsRoute
  '/dashboard/verify': typeof AuthenticatedDashboardVerifyRoute
  '/dashboard/wallet': typeof AuthenticatedDashboardWalletRoute
  '/api/public/didit-webhook': typeof ApiPublicDiditWebhookRoute
  '/api/public/ligdicash-webhook': typeof ApiPublicLigdicashWebhookRoute
  '/api/public/pawapay-webhook': typeof ApiPublicPawapayWebhookRoute
  '/api/public/send-notification': typeof ApiPublicSendNotificationRoute
  '/api/public/sync-wallet': typeof ApiPublicSyncWalletRoute
  '/api/public/withdraw': typeof ApiPublicWithdrawRoute
  '/api/v1/charges': typeof ApiV1ChargesRouteWithChildren
  '/api/v1/payouts': typeof ApiV1PayoutsRoute
  '/api/webhooks/didit': typeof ApiWebhooksDiditRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/admin/merchants/$id': typeof AuthenticatedAdminMerchantsIdRoute
  '/api/public/pay/$slug': typeof ApiPublicPaySlugRoute
  '/api/public/tx-status/$id': typeof ApiPublicTxStatusIdRoute
  '/api/public/tx-timeout/$id': typeof ApiPublicTxTimeoutIdRoute
  '/api/v1/charges/$id': typeof ApiV1ChargesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/complete-profile': typeof AuthenticatedCompleteProfileRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/company/about': typeof CompanyAboutRoute
  '/company/contact': typeof CompanyContactRoute
  '/company/pricing': typeof CompanyPricingRoute
  '/developers/api': typeof DevelopersApiRoute
  '/developers/sdks': typeof DevelopersSdksRoute
  '/legal/aml': typeof LegalAmlRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/pay/$slug': typeof PaySlugRoute
  '/products/ecommerce': typeof ProductsEcommerceRoute
  '/products/pay-in': typeof ProductsPayInRoute
  '/products/pay-out': typeof ProductsPayOutRoute
  '/products/payment-links': typeof ProductsPaymentLinksRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/compliance': typeof AuthenticatedAdminComplianceRoute
  '/admin/finance': typeof AuthenticatedAdminFinanceRoute
  '/admin/live': typeof AuthenticatedAdminLiveRoute
  '/admin/merchants': typeof AuthenticatedAdminMerchantsRouteWithChildren
  '/admin/risk': typeof AuthenticatedAdminRiskRoute
  '/dashboard/admin': typeof AuthenticatedDashboardAdminRoute
  '/dashboard/api-keys': typeof AuthenticatedDashboardApiKeysRoute
  '/dashboard/payment-links': typeof AuthenticatedDashboardPaymentLinksRoute
  '/dashboard/payouts': typeof AuthenticatedDashboardPayoutsRoute
  '/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/dashboard/team': typeof AuthenticatedDashboardTeamRoute
  '/dashboard/transactions': typeof AuthenticatedDashboardTransactionsRoute
  '/dashboard/verify': typeof AuthenticatedDashboardVerifyRoute
  '/dashboard/wallet': typeof AuthenticatedDashboardWalletRoute
  '/api/public/didit-webhook': typeof ApiPublicDiditWebhookRoute
  '/api/public/ligdicash-webhook': typeof ApiPublicLigdicashWebhookRoute
  '/api/public/pawapay-webhook': typeof ApiPublicPawapayWebhookRoute
  '/api/public/send-notification': typeof ApiPublicSendNotificationRoute
  '/api/public/sync-wallet': typeof ApiPublicSyncWalletRoute
  '/api/public/withdraw': typeof ApiPublicWithdrawRoute
  '/api/v1/charges': typeof ApiV1ChargesRouteWithChildren
  '/api/v1/payouts': typeof ApiV1PayoutsRoute
  '/api/webhooks/didit': typeof ApiWebhooksDiditRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/admin/merchants/$id': typeof AuthenticatedAdminMerchantsIdRoute
  '/api/public/pay/$slug': typeof ApiPublicPaySlugRoute
  '/api/public/tx-status/$id': typeof ApiPublicTxStatusIdRoute
  '/api/public/tx-timeout/$id': typeof ApiPublicTxTimeoutIdRoute
  '/api/v1/charges/$id': typeof ApiV1ChargesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/settings': typeof SettingsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteRouteWithChildren
  '/_authenticated/complete-profile': typeof AuthenticatedCompleteProfileRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/company/about': typeof CompanyAboutRoute
  '/company/contact': typeof CompanyContactRoute
  '/company/pricing': typeof CompanyPricingRoute
  '/developers/api': typeof DevelopersApiRoute
  '/developers/sdks': typeof DevelopersSdksRoute
  '/legal/aml': typeof LegalAmlRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/pay/$slug': typeof PaySlugRoute
  '/products/ecommerce': typeof ProductsEcommerceRoute
  '/products/pay-in': typeof ProductsPayInRoute
  '/products/pay-out': typeof ProductsPayOutRoute
  '/products/payment-links': typeof ProductsPaymentLinksRoute
  '/_authenticated/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/_authenticated/admin/compliance': typeof AuthenticatedAdminComplianceRoute
  '/_authenticated/admin/finance': typeof AuthenticatedAdminFinanceRoute
  '/_authenticated/admin/live': typeof AuthenticatedAdminLiveRoute
  '/_authenticated/admin/merchants': typeof AuthenticatedAdminMerchantsRouteWithChildren
  '/_authenticated/admin/risk': typeof AuthenticatedAdminRiskRoute
  '/_authenticated/dashboard/admin': typeof AuthenticatedDashboardAdminRoute
  '/_authenticated/dashboard/api-keys': typeof AuthenticatedDashboardApiKeysRoute
  '/_authenticated/dashboard/payment-links': typeof AuthenticatedDashboardPaymentLinksRoute
  '/_authenticated/dashboard/payouts': typeof AuthenticatedDashboardPayoutsRoute
  '/_authenticated/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/_authenticated/dashboard/team': typeof AuthenticatedDashboardTeamRoute
  '/_authenticated/dashboard/transactions': typeof AuthenticatedDashboardTransactionsRoute
  '/_authenticated/dashboard/verify': typeof AuthenticatedDashboardVerifyRoute
  '/_authenticated/dashboard/wallet': typeof AuthenticatedDashboardWalletRoute
  '/api/public/didit-webhook': typeof ApiPublicDiditWebhookRoute
  '/api/public/ligdicash-webhook': typeof ApiPublicLigdicashWebhookRoute
  '/api/public/pawapay-webhook': typeof ApiPublicPawapayWebhookRoute
  '/api/public/send-notification': typeof ApiPublicSendNotificationRoute
  '/api/public/sync-wallet': typeof ApiPublicSyncWalletRoute
  '/api/public/withdraw': typeof ApiPublicWithdrawRoute
  '/api/v1/charges': typeof ApiV1ChargesRouteWithChildren
  '/api/v1/payouts': typeof ApiV1PayoutsRoute
  '/api/webhooks/didit': typeof ApiWebhooksDiditRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/admin/merchants/$id': typeof AuthenticatedAdminMerchantsIdRoute
  '/api/public/pay/$slug': typeof ApiPublicPaySlugRoute
  '/api/public/tx-status/$id': typeof ApiPublicTxStatusIdRoute
  '/api/public/tx-timeout/$id': typeof ApiPublicTxTimeoutIdRoute
  '/api/v1/charges/$id': typeof ApiV1ChargesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/admin'
    | '/dashboard'
    | '/complete-profile'
    | '/onboarding'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/company/about'
    | '/company/contact'
    | '/company/pricing'
    | '/developers/api'
    | '/developers/sdks'
    | '/legal/aml'
    | '/legal/privacy'
    | '/legal/terms'
    | '/pay/$slug'
    | '/products/ecommerce'
    | '/products/pay-in'
    | '/products/pay-out'
    | '/products/payment-links'
    | '/admin/audit'
    | '/admin/compliance'
    | '/admin/finance'
    | '/admin/live'
    | '/admin/merchants'
    | '/admin/risk'
    | '/dashboard/admin'
    | '/dashboard/api-keys'
    | '/dashboard/payment-links'
    | '/dashboard/payouts'
    | '/dashboard/settings'
    | '/dashboard/team'
    | '/dashboard/transactions'
    | '/dashboard/verify'
    | '/dashboard/wallet'
    | '/api/public/didit-webhook'
    | '/api/public/ligdicash-webhook'
    | '/api/public/pawapay-webhook'
    | '/api/public/send-notification'
    | '/api/public/sync-wallet'
    | '/api/public/withdraw'
    | '/api/v1/charges'
    | '/api/v1/payouts'
    | '/api/webhooks/didit'
    | '/admin/'
    | '/dashboard/'
    | '/admin/merchants/$id'
    | '/api/public/pay/$slug'
    | '/api/public/tx-status/$id'
    | '/api/public/tx-timeout/$id'
    | '/api/v1/charges/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/complete-profile'
    | '/onboarding'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/company/about'
    | '/company/contact'
    | '/company/pricing'
    | '/developers/api'
    | '/developers/sdks'
    | '/legal/aml'
    | '/legal/privacy'
    | '/legal/terms'
    | '/pay/$slug'
    | '/products/ecommerce'
    | '/products/pay-in'
    | '/products/pay-out'
    | '/products/payment-links'
    | '/admin/audit'
    | '/admin/compliance'
    | '/admin/finance'
    | '/admin/live'
    | '/admin/merchants'
    | '/admin/risk'
    | '/dashboard/admin'
    | '/dashboard/api-keys'
    | '/dashboard/payment-links'
    | '/dashboard/payouts'
    | '/dashboard/settings'
    | '/dashboard/team'
    | '/dashboard/transactions'
    | '/dashboard/verify'
    | '/dashboard/wallet'
    | '/api/public/didit-webhook'
    | '/api/public/ligdicash-webhook'
    | '/api/public/pawapay-webhook'
    | '/api/public/send-notification'
    | '/api/public/sync-wallet'
    | '/api/public/withdraw'
    | '/api/v1/charges'
    | '/api/v1/payouts'
    | '/api/webhooks/didit'
    | '/admin'
    | '/dashboard'
    | '/admin/merchants/$id'
    | '/api/public/pay/$slug'
    | '/api/public/tx-status/$id'
    | '/api/public/tx-timeout/$id'
    | '/api/v1/charges/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/settings'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/complete-profile'
    | '/_authenticated/onboarding'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/company/about'
    | '/company/contact'
    | '/company/pricing'
    | '/developers/api'
    | '/developers/sdks'
    | '/legal/aml'
    | '/legal/privacy'
    | '/legal/terms'
    | '/pay/$slug'
    | '/products/ecommerce'
    | '/products/pay-in'
    | '/products/pay-out'
    | '/products/payment-links'
    | '/_authenticated/admin/audit'
    | '/_authenticated/admin/compliance'
    | '/_authenticated/admin/finance'
    | '/_authenticated/admin/live'
    | '/_authenticated/admin/merchants'
    | '/_authenticated/admin/risk'
    | '/_authenticated/dashboard/admin'
    | '/_authenticated/dashboard/api-keys'
    | '/_authenticated/dashboard/payment-links'
    | '/_authenticated/dashboard/payouts'
    | '/_authenticated/dashboard/settings'
    | '/_authenticated/dashboard/team'
    | '/_authenticated/dashboard/transactions'
    | '/_authenticated/dashboard/verify'
    | '/_authenticated/dashboard/wallet'
    | '/api/public/didit-webhook'
    | '/api/public/ligdicash-webhook'
    | '/api/public/pawapay-webhook'
    | '/api/public/send-notification'
    | '/api/public/sync-wallet'
    | '/api/public/withdraw'
    | '/api/v1/charges'
    | '/api/v1/payouts'
    | '/api/webhooks/didit'
    | '/_authenticated/admin/'
    | '/_authenticated/dashboard/'
    | '/_authenticated/admin/merchants/$id'
    | '/api/public/pay/$slug'
    | '/api/public/tx-status/$id'
    | '/api/public/tx-timeout/$id'
    | '/api/v1/charges/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  CompanyAboutRoute: typeof CompanyAboutRoute
  CompanyContactRoute: typeof CompanyContactRoute
  CompanyPricingRoute: typeof CompanyPricingRoute
  DevelopersApiRoute: typeof DevelopersApiRoute
  DevelopersSdksRoute: typeof DevelopersSdksRoute
  LegalAmlRoute: typeof LegalAmlRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalTermsRoute: typeof LegalTermsRoute
  PaySlugRoute: typeof PaySlugRoute
  ProductsEcommerceRoute: typeof ProductsEcommerceRoute
  ProductsPayInRoute: typeof ProductsPayInRoute
  ProductsPayOutRoute: typeof ProductsPayOutRoute
  ProductsPaymentLinksRoute: typeof ProductsPaymentLinksRoute
  ApiPublicDiditWebhookRoute: typeof ApiPublicDiditWebhookRoute
  ApiPublicLigdicashWebhookRoute: typeof ApiPublicLigdicashWebhookRoute
  ApiPublicPawapayWebhookRoute: typeof ApiPublicPawapayWebhookRoute
  ApiPublicSendNotificationRoute: typeof ApiPublicSendNotificationRoute
  ApiPublicSyncWalletRoute: typeof ApiPublicSyncWalletRoute
  ApiPublicWithdrawRoute: typeof ApiPublicWithdrawRoute
  ApiV1ChargesRoute: typeof ApiV1ChargesRouteWithChildren
  ApiV1PayoutsRoute: typeof ApiV1PayoutsRoute
  ApiWebhooksDiditRoute: typeof ApiWebhooksDiditRoute
  ApiPublicPaySlugRoute: typeof ApiPublicPaySlugRoute
  ApiPublicTxStatusIdRoute: typeof ApiPublicTxStatusIdRoute
  ApiPublicTxTimeoutIdRoute: typeof ApiPublicTxTimeoutIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/payment-links': {
      id: '/products/payment-links'
      path: '/products/payment-links'
      fullPath: '/products/payment-links'
      preLoaderRoute: typeof ProductsPaymentLinksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/pay-out': {
      id: '/products/pay-out'
      path: '/products/pay-out'
      fullPath: '/products/pay-out'
      preLoaderRoute: typeof ProductsPayOutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/pay-in': {
      id: '/products/pay-in'
      path: '/products/pay-in'
      fullPath: '/products/pay-in'
      preLoaderRoute: typeof ProductsPayInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/ecommerce': {
      id: '/products/ecommerce'
      path: '/products/ecommerce'
      fullPath: '/products/ecommerce'
      preLoaderRoute: typeof ProductsEcommerceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay/$slug': {
      id: '/pay/$slug'
      path: '/pay/$slug'
      fullPath: '/pay/$slug'
      preLoaderRoute: typeof PaySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/aml': {
      id: '/legal/aml'
      path: '/legal/aml'
      fullPath: '/legal/aml'
      preLoaderRoute: typeof LegalAmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developers/sdks': {
      id: '/developers/sdks'
      path: '/developers/sdks'
      fullPath: '/developers/sdks'
      preLoaderRoute: typeof DevelopersSdksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developers/api': {
      id: '/developers/api'
      path: '/developers/api'
      fullPath: '/developers/api'
      preLoaderRoute: typeof DevelopersApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/pricing': {
      id: '/company/pricing'
      path: '/company/pricing'
      fullPath: '/company/pricing'
      preLoaderRoute: typeof CompanyPricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/contact': {
      id: '/company/contact'
      path: '/company/contact'
      fullPath: '/company/contact'
      preLoaderRoute: typeof CompanyContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/about': {
      id: '/company/about'
      path: '/company/about'
      fullPath: '/company/about'
      preLoaderRoute: typeof CompanyAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/auth/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/complete-profile': {
      id: '/_authenticated/complete-profile'
      path: '/complete-profile'
      fullPath: '/complete-profile'
      preLoaderRoute: typeof AuthenticatedCompleteProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/api/webhooks/didit': {
      id: '/api/webhooks/didit'
      path: '/api/webhooks/didit'
      fullPath: '/api/webhooks/didit'
      preLoaderRoute: typeof ApiWebhooksDiditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/payouts': {
      id: '/api/v1/payouts'
      path: '/api/v1/payouts'
      fullPath: '/api/v1/payouts'
      preLoaderRoute: typeof ApiV1PayoutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/charges': {
      id: '/api/v1/charges'
      path: '/api/v1/charges'
      fullPath: '/api/v1/charges'
      preLoaderRoute: typeof ApiV1ChargesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/withdraw': {
      id: '/api/public/withdraw'
      path: '/api/public/withdraw'
      fullPath: '/api/public/withdraw'
      preLoaderRoute: typeof ApiPublicWithdrawRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sync-wallet': {
      id: '/api/public/sync-wallet'
      path: '/api/public/sync-wallet'
      fullPath: '/api/public/sync-wallet'
      preLoaderRoute: typeof ApiPublicSyncWalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/send-notification': {
      id: '/api/public/send-notification'
      path: '/api/public/send-notification'
      fullPath: '/api/public/send-notification'
      preLoaderRoute: typeof ApiPublicSendNotificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/pawapay-webhook': {
      id: '/api/public/pawapay-webhook'
      path: '/api/public/pawapay-webhook'
      fullPath: '/api/public/pawapay-webhook'
      preLoaderRoute: typeof ApiPublicPawapayWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ligdicash-webhook': {
      id: '/api/public/ligdicash-webhook'
      path: '/api/public/ligdicash-webhook'
      fullPath: '/api/public/ligdicash-webhook'
      preLoaderRoute: typeof ApiPublicLigdicashWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/didit-webhook': {
      id: '/api/public/didit-webhook'
      path: '/api/public/didit-webhook'
      fullPath: '/api/public/didit-webhook'
      preLoaderRoute: typeof ApiPublicDiditWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard/wallet': {
      id: '/_authenticated/dashboard/wallet'
      path: '/wallet'
      fullPath: '/dashboard/wallet'
      preLoaderRoute: typeof AuthenticatedDashboardWalletRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/verify': {
      id: '/_authenticated/dashboard/verify'
      path: '/verify'
      fullPath: '/dashboard/verify'
      preLoaderRoute: typeof AuthenticatedDashboardVerifyRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/transactions': {
      id: '/_authenticated/dashboard/transactions'
      path: '/transactions'
      fullPath: '/dashboard/transactions'
      preLoaderRoute: typeof AuthenticatedDashboardTransactionsRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/team': {
      id: '/_authenticated/dashboard/team'
      path: '/team'
      fullPath: '/dashboard/team'
      preLoaderRoute: typeof AuthenticatedDashboardTeamRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/settings': {
      id: '/_authenticated/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof AuthenticatedDashboardSettingsRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/payouts': {
      id: '/_authenticated/dashboard/payouts'
      path: '/payouts'
      fullPath: '/dashboard/payouts'
      preLoaderRoute: typeof AuthenticatedDashboardPayoutsRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/payment-links': {
      id: '/_authenticated/dashboard/payment-links'
      path: '/payment-links'
      fullPath: '/dashboard/payment-links'
      preLoaderRoute: typeof AuthenticatedDashboardPaymentLinksRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/api-keys': {
      id: '/_authenticated/dashboard/api-keys'
      path: '/api-keys'
      fullPath: '/dashboard/api-keys'
      preLoaderRoute: typeof AuthenticatedDashboardApiKeysRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/admin': {
      id: '/_authenticated/dashboard/admin'
      path: '/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof AuthenticatedDashboardAdminRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/admin/risk': {
      id: '/_authenticated/admin/risk'
      path: '/risk'
      fullPath: '/admin/risk'
      preLoaderRoute: typeof AuthenticatedAdminRiskRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/merchants': {
      id: '/_authenticated/admin/merchants'
      path: '/merchants'
      fullPath: '/admin/merchants'
      preLoaderRoute: typeof AuthenticatedAdminMerchantsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/live': {
      id: '/_authenticated/admin/live'
      path: '/live'
      fullPath: '/admin/live'
      preLoaderRoute: typeof AuthenticatedAdminLiveRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/finance': {
      id: '/_authenticated/admin/finance'
      path: '/finance'
      fullPath: '/admin/finance'
      preLoaderRoute: typeof AuthenticatedAdminFinanceRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/compliance': {
      id: '/_authenticated/admin/compliance'
      path: '/compliance'
      fullPath: '/admin/compliance'
      preLoaderRoute: typeof AuthenticatedAdminComplianceRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/audit': {
      id: '/_authenticated/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AuthenticatedAdminAuditRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/api/v1/charges/$id': {
      id: '/api/v1/charges/$id'
      path: '/$id'
      fullPath: '/api/v1/charges/$id'
      preLoaderRoute: typeof ApiV1ChargesIdRouteImport
      parentRoute: typeof ApiV1ChargesRoute
    }
    '/api/public/tx-timeout/$id': {
      id: '/api/public/tx-timeout/$id'
      path: '/api/public/tx-timeout/$id'
      fullPath: '/api/public/tx-timeout/$id'
      preLoaderRoute: typeof ApiPublicTxTimeoutIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/tx-status/$id': {
      id: '/api/public/tx-status/$id'
      path: '/api/public/tx-status/$id'
      fullPath: '/api/public/tx-status/$id'
      preLoaderRoute: typeof ApiPublicTxStatusIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/pay/$slug': {
      id: '/api/public/pay/$slug'
      path: '/api/public/pay/$slug'
      fullPath: '/api/public/pay/$slug'
      preLoaderRoute: typeof ApiPublicPaySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/merchants/$id': {
      id: '/_authenticated/admin/merchants/$id'
      path: '/$id'
      fullPath: '/admin/merchants/$id'
      preLoaderRoute: typeof AuthenticatedAdminMerchantsIdRouteImport
      parentRoute: typeof AuthenticatedAdminMerchantsRoute
    }
  }
}

interface AuthenticatedAdminMerchantsRouteChildren {
  AuthenticatedAdminMerchantsIdRoute: typeof AuthenticatedAdminMerchantsIdRoute
}

const AuthenticatedAdminMerchantsRouteChildren: AuthenticatedAdminMerchantsRouteChildren =
  {
    AuthenticatedAdminMerchantsIdRoute: AuthenticatedAdminMerchantsIdRoute,
  }

const AuthenticatedAdminMerchantsRouteWithChildren =
  AuthenticatedAdminMerchantsRoute._addFileChildren(
    AuthenticatedAdminMerchantsRouteChildren,
  )

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminAuditRoute: typeof AuthenticatedAdminAuditRoute
  AuthenticatedAdminComplianceRoute: typeof AuthenticatedAdminComplianceRoute
  AuthenticatedAdminFinanceRoute: typeof AuthenticatedAdminFinanceRoute
  AuthenticatedAdminLiveRoute: typeof AuthenticatedAdminLiveRoute
  AuthenticatedAdminMerchantsRoute: typeof AuthenticatedAdminMerchantsRouteWithChildren
  AuthenticatedAdminRiskRoute: typeof AuthenticatedAdminRiskRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminAuditRoute: AuthenticatedAdminAuditRoute,
    AuthenticatedAdminComplianceRoute: AuthenticatedAdminComplianceRoute,
    AuthenticatedAdminFinanceRoute: AuthenticatedAdminFinanceRoute,
    AuthenticatedAdminLiveRoute: AuthenticatedAdminLiveRoute,
    AuthenticatedAdminMerchantsRoute:
      AuthenticatedAdminMerchantsRouteWithChildren,
    AuthenticatedAdminRiskRoute: AuthenticatedAdminRiskRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedDashboardRouteRouteChildren {
  AuthenticatedDashboardAdminRoute: typeof AuthenticatedDashboardAdminRoute
  AuthenticatedDashboardApiKeysRoute: typeof AuthenticatedDashboardApiKeysRoute
  AuthenticatedDashboardPaymentLinksRoute: typeof AuthenticatedDashboardPaymentLinksRoute
  AuthenticatedDashboardPayoutsRoute: typeof AuthenticatedDashboardPayoutsRoute
  AuthenticatedDashboardSettingsRoute: typeof AuthenticatedDashboardSettingsRoute
  AuthenticatedDashboardTeamRoute: typeof AuthenticatedDashboardTeamRoute
  AuthenticatedDashboardTransactionsRoute: typeof AuthenticatedDashboardTransactionsRoute
  AuthenticatedDashboardVerifyRoute: typeof AuthenticatedDashboardVerifyRoute
  AuthenticatedDashboardWalletRoute: typeof AuthenticatedDashboardWalletRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
}

const AuthenticatedDashboardRouteRouteChildren: AuthenticatedDashboardRouteRouteChildren =
  {
    AuthenticatedDashboardAdminRoute: AuthenticatedDashboardAdminRoute,
    AuthenticatedDashboardApiKeysRoute: AuthenticatedDashboardApiKeysRoute,
    AuthenticatedDashboardPaymentLinksRoute:
      AuthenticatedDashboardPaymentLinksRoute,
    AuthenticatedDashboardPayoutsRoute: AuthenticatedDashboardPayoutsRoute,
    AuthenticatedDashboardSettingsRoute: AuthenticatedDashboardSettingsRoute,
    AuthenticatedDashboardTeamRoute: AuthenticatedDashboardTeamRoute,
    AuthenticatedDashboardTransactionsRoute:
      AuthenticatedDashboardTransactionsRoute,
    AuthenticatedDashboardVerifyRoute: AuthenticatedDashboardVerifyRoute,
    AuthenticatedDashboardWalletRoute: AuthenticatedDashboardWalletRoute,
    AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  }

const AuthenticatedDashboardRouteRouteWithChildren =
  AuthenticatedDashboardRouteRoute._addFileChildren(
    AuthenticatedDashboardRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedDashboardRouteRoute: typeof AuthenticatedDashboardRouteRouteWithChildren
  AuthenticatedCompleteProfileRoute: typeof AuthenticatedCompleteProfileRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedDashboardRouteRoute:
    AuthenticatedDashboardRouteRouteWithChildren,
  AuthenticatedCompleteProfileRoute: AuthenticatedCompleteProfileRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ApiV1ChargesRouteChildren {
  ApiV1ChargesIdRoute: typeof ApiV1ChargesIdRoute
}

const ApiV1ChargesRouteChildren: ApiV1ChargesRouteChildren = {
  ApiV1ChargesIdRoute: ApiV1ChargesIdRoute,
}

const ApiV1ChargesRouteWithChildren = ApiV1ChargesRoute._addFileChildren(
  ApiV1ChargesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  SettingsRoute: SettingsRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  CompanyAboutRoute: CompanyAboutRoute,
  CompanyContactRoute: CompanyContactRoute,
  CompanyPricingRoute: CompanyPricingRoute,
  DevelopersApiRoute: DevelopersApiRoute,
  DevelopersSdksRoute: DevelopersSdksRoute,
  LegalAmlRoute: LegalAmlRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalTermsRoute: LegalTermsRoute,
  PaySlugRoute: PaySlugRoute,
  ProductsEcommerceRoute: ProductsEcommerceRoute,
  ProductsPayInRoute: ProductsPayInRoute,
  ProductsPayOutRoute: ProductsPayOutRoute,
  ProductsPaymentLinksRoute: ProductsPaymentLinksRoute,
  ApiPublicDiditWebhookRoute: ApiPublicDiditWebhookRoute,
  ApiPublicLigdicashWebhookRoute: ApiPublicLigdicashWebhookRoute,
  ApiPublicPawapayWebhookRoute: ApiPublicPawapayWebhookRoute,
  ApiPublicSendNotificationRoute: ApiPublicSendNotificationRoute,
  ApiPublicSyncWalletRoute: ApiPublicSyncWalletRoute,
  ApiPublicWithdrawRoute: ApiPublicWithdrawRoute,
  ApiV1ChargesRoute: ApiV1ChargesRouteWithChildren,
  ApiV1PayoutsRoute: ApiV1PayoutsRoute,
  ApiWebhooksDiditRoute: ApiWebhooksDiditRoute,
  ApiPublicPaySlugRoute: ApiPublicPaySlugRoute,
  ApiPublicTxStatusIdRoute: ApiPublicTxStatusIdRoute,
  ApiPublicTxTimeoutIdRoute: ApiPublicTxTimeoutIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
